### ISSUE TITLE
Binding mode

### ISSUE THREAD

**Issue by adnanademovic** [Flybrix/flybrix-firmware#19]
We could add a serial command to trigger the binding process.

This would involve holding the DAT pin low for ~10 seconds, while blinking the LEDs in a pattern of some kind. The app would have to offer instructions (essentially remove and reattach the R/C receiver while the flightboard is in rebinding mode. After 10 seconds, we would reconfigure the DAT pin as a timer again.

**Comment by rjwalters** [comment]
not needed for the new receiver design
