### ISSUE TITLE
Trying to open up 1.5.0 firmware in Teensy gives "data beyond chip size, yikes!"

### ISSUE THREAD

**Issue by dgrant** [Flybrix/flybrix-firmware#21]
```
23:02:50.870: File "flybrix-firmware-1.5.0.hex". 103672 bytes, 161% used
23:02:50.870: File contains data beyond chip size, yikes!
```

Any idea?

**Comment by dgrant** [comment]
In my .teensy file it says:

code_size=64512

Maybe I can change that to something else?

**Comment by rjwalters** [comment]
Hi David,

It might be better to write to "support@flybrix.com" so we can make a
zendesk ticket for this.

Are you trying to compile and install from within the Arduino IDE or are
you trying to install the firmware .hex file with the teensyloader app?

I have seen similar issues with bad USB cables in the past believe it or
not...

Best,

Robb
