### ISSUE TITLE
thrust PID control implementation

### ISSUE THREAD

**Issue by rjwalters** [Flybrix/flybrix-firmware#3]
The cascaded PID controller for thrust is not really implemented properly yet. It's nice to use the same controller code that we use for our other three control vectors, but the thrust slave loop isn't equivalent to the gyroscope-backed rotation slave loops. We do not have an ascent/descent sensor that offers better bandwidth than the derivative of the barometer data. (It isn't even clear what sensor would work here -- forward optical flow? doppler ultrasound?)

**We should probably explicitly guard against the pidBypass modes that would put us into cascaded control mode for thrust.**

Slave-only mode can still make sense if we use the derivative of the state altitude estimate -- but we would need to special case some of the command code so that our thrust joystick is bi-directional to allow both ascent and descent.

**Comment by adnanademovic** [comment]
Should we just do it by filtering the pidBypass mode, so that we ignore bad bypasses, even if they are sent?

**Comment by rjwalters** [comment]
We can send a rejection code back too, right?

**Comment by adnanademovic** [comment]
Yes. We could make a verification with returned debug data for each subsystem that could detect that something is wrong. That would be a future proof solution.

**Comment by adnanademovic** [comment]
This fixes that problem. We can easily add any verification now, so we should probably use this branch to add more verification.
