### ISSUE TITLE
forced calibration when arming

### ISSUE THREAD

**Issue by rjwalters** [Flybrix/flybrix-firmware#6]
The default behavior now is to assume that the flyer is level when we arm and to measure and store the orientation of the flight board with respect to the flyer coordinate system. This is intentional to simplify flight for new models, but can be annoying if flying the same model repeatedly, or if the user wants to take off without being flat without having to trim in flight.

An alternative is to store the rotation matrix coordinates and accelBias in the eeprom and create a flag to enable/disable recalibration during the arming sequence. This seems like something we can support without changing the default behavior if enough of our advanced users want the feature -- but it will require bumping the minor version number.

**Comment by Jukkorsis** [comment]
Auto calibrating would be great.
My flyer appears (after investigating with the Chrome app) to have a bias toward tilting backwards and rotating clockwise.

**Comment by peterlada** [comment]
Mine has the same issue. Rotating clockwise a good amount and tilting back a little.

**Comment by rjwalters** [comment]
v1.6.0 moves our state estimation to a new UKF and adds the ability to calibrate the imu from the app.
