### ISSUE TITLE
Improve serial feedback

### ISSUE THREAD

**Issue by adnanademovic** [Flybrix/flybrix-firmware#8]
Currently, we are providing very low feedback on what is going on when things go wrong. We should use DebugPrint/f to send more detailed information in the case of errors.
Any code path that we can get into only as a result of an issue should provide that type of feedback for easier problem solving.
We could even consider a more lightweight approach of sending error codes and enumerating all possible issues.

**Comment by rjwalters** [comment]
DebugPrintf works great and is now color coded in the app too
